### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by crifonju** [DBinaghi/plugin-ItemDuplicator#1]
Hello there!
thanks for the contribution. I was looking exactly for something like this. Unfortunately, I'm unable to install the plugin onto Omeka, is there anything I should do that I'm not aware of?

Thanks in advance,
Cris.

**Comment by DBinaghi** [comment]
Plugin is still under development. As for now, some parts are missing, and some parts need to be changed in the core. Please refer to https://forum.omeka.org/t/duplicate-an-item/4694 for more info
