### ISSUE TITLE
Conflict with CSV Import

### ISSUE THREAD

**Issue by sbarnessckls** [DBinaghi/plugin-ItemDuplicator#2]
This plugin appears to conflict with csv imports into Omeka.   See [https://forum.omeka.org/t/csvimport-stops/11574](https://forum.omeka.org/t/csvimport-stops/11574) for the few details available.  Once ItemDuplicator was deactivated, the upload completed successfully.  I find ItemDuplicator very useful, so hope the conflict can be resolved!

**Comment by zerocrates** [comment]
We clearly filed issues at basically the same time, I've closed mine as they're duplicates. I'll just copy over the relevant part:

> The solution is probably simple: just check if getRequest() returns null, and return early out of the before_save_item hook if so.

**Comment by DBinaghi** [comment]
Hi. Thanks for letting me know, and sorry for not working on this any earlier (just noticed the open issue, guess I missed any notification).
I cannot have CSV Import working on my installation, so I've tried to modify the ItemDuplicatorPlugin.php file; @sbarnessckls, would it be possible for you to substitute the code in your installation and check whether the conflict is solved now, and let me know, please?
Thanks
