### ISSUE TITLE
Port to Omeka S

### ISSUE THREAD

**Issue by raboof** [DBinaghi/plugin-ItemDuplicator#4]
Has there been any effort to port this plugin to Omeka S?

I saw https://omeka.org/s/modules/ItemCopy/ exists, but I'm a bit reluctant to include the API keys in the javascript to allow it to make Ajax requests to the REST API...

**Comment by raboof** [comment]
I started on the first 'mechanical' changes of the port a bit at https://codeberg.org/eicas/Omeka-S-module-ItemDuplicator - though the actual 'meat' (actually duplicating the item) is still to be done - I'm not too familiar with how Omeka (or Laminas in general) works yet ;)

**Comment by DBinaghi** [comment]
Hello. 
Sorry, but I don't work with Omeka S, so I would not know where to start from. You're more than welcome to create a port for that system, though.

**Comment by raboof** [comment]
Thanks for the confirmation! I'm happy to say https://codeberg.org/eicas/Omeka-S-module-ItemDuplicator is now far enough along that it meets our most basic needs for duplicating items, though I'm sure it doesn't implement all the options correctly yet.

**Comment by DBinaghi** [comment]
I'm glad you've managed to port it.
Please be aware of some issues with PHP 8, hence some changes in the code for version 1.4
